name: Build on request
on: [workflow_dispatch]

jobs:
  Windows:
    name: Build windows version
    runs-on: ubuntu-20.04 # Ubuntu é mais rápido, mas precisa do MXE
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install MXE & Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg2
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B6165C
        sudo add-apt-repository "deb [arch=amd64] http://pkg.mxe.cc/repos/apt/focal main"
        sudo apt-get update
        sudo apt-get install -y mxe-i686-w64-mingw32.static-boost mxe-i686-w64-mingw32.static-glew mxe-i686-w64-mingw32.static-libzip mxe-i686-w64-mingw32.static-physfs mxe-i686-w64-mingw32.static-openssl mxe-i686-w64-mingw32.static-luajit cmake

    - name: Compile OTClient
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/lib/mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake -DOTC_COMPILE_STATIC=ON -G "Unix Makefiles"
        make -j$(nproc)

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: otclient-windows
        path: build/otclient.exe
