name: Compilar Cliente
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Instalar Dependencias (Forçando Limpeza)
        run: |
          # Removemos o diretório de ports se estiver corrompido e instalamos do zero
          vcpkg install zlib libzip glew openssl physfs luajit --triplet x86-windows-static --recurse

      - name: Compilar com CMake
        shell: bash
        run: |
          mkdir build && cd build
          # Adicionamos uma flag para ignorar o wrapper que está dando erro (vcpkg-cmake-wrapper.cmake)
          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
                   -DVCPKG_TARGET_TRIPLET=x86-windows-static \
                   -DOTC_COMPILE_STATIC=ON \
                   -DZLIB_LIBRARY="C:/vcpkg/installed/x86-windows-static/lib/zlib.lib" \
                   -DZLIB_INCLUDE_DIR="C:/vcpkg/installed/x86-windows-static/include" \
                   -D_VCPKG_INSTALLED_DIR="C:/vcpkg/installed"
          
          cmake --build . --config Release --parallel 4

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: otclient-windows
          path: build/Release/otclient.exe
