name: Compilar Cliente
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Instalar Dependencias (vcpkg)
        run: |
          # Instalamos tudo de novo para garantir que os arquivos existam no disco
          vcpkg install glew openssl physfs luajit zlib libzip --triplet x86-windows-static

      - name: Compilar com CMake
        shell: bash
        run: |
          mkdir build && cd build
          # O pulo do gato: Passamos o caminho direto da ZLIB do vcpkg nas variáveis do CMake
          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
                   -DVCPKG_TARGET_TRIPLET=x86-windows-static \
                   -DOTC_COMPILE_STATIC=ON \
                   -DZLIB_LIBRARY="C:/vcpkg/installed/x86-windows-static/lib/zlib.lib" \
                   -DZLIB_INCLUDE_DIR="C:/vcpkg/installed/x86-windows-static/include" \
                   -DLIBZIP_LIBRARY="C:/vcpkg/installed/x86-windows-static/lib/libzip.lib" \
                   -DLIBZIP_INCLUDE_DIR="C:/vcpkg/installed/x86-windows-static/include"
          
          cmake --build . --config Release --parallel 4

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: otclient-windows
          path: build/Release/otclient.exe
